DROP DATABASE [SPOTIFY];
CREATE DATABASE [SPOTIFY];

USE [SPOTIFY];

DROP INDEX idx_ARTIST_Name ON [ARTIST];
DROP INDEX idx_ALBUM_Name ON [ALBUM];
DROP INDEX idx_SONG_Title ON [SONG];
DROP INDEX idx_USER_Name ON [USER];

DROP TABLE [STREAM];
DROP TABLE [USER];
DROP TABLE [SONG_GENRE];
DROP TABLE [SONG];
DROP TABLE [GENRE];
DROP TABLE [ALBUM];
DROP TABLE [Artist];

CREATE TABLE [ARTIST] (
	[ID]		UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[Name]		NVARCHAR(128)

	CONSTRAINT PK_ARTIST PRIMARY KEY ([ID])
);

CREATE TABLE [ALBUM] (
	[ID]			UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[ArtistID]		UNIQUEIDENTIFIER,
	[Name]			NVARCHAR(128),
	[ReleaseYear]	INT

	CONSTRAINT PK_ALBUM PRIMARY KEY ([ID]),
	CONSTRAINT FK_ALBUM_ArtistID FOREIGN KEY ([ArtistID]) REFERENCES [ARTIST] ([ID])
);

CREATE TABLE [GENRE] (
	[ID]		UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[Name]		NVARCHAR(32)

	CONSTRAINT PK_GENRE PRIMARY KEY ([ID])
);

CREATE TABLE [SONG] (
	[ID]					UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[AlbumID]				UNIQUEIDENTIFIER,
	[Title]					NVARCHAR(128),
	[Duration]				INT,
	[Duration_Hours]		INT NULL,
	[Duration_Minutes]		INT NULL,
	[Duration_Seconds]		INT NULL

	CONSTRAINT PK_SONG PRIMARY KEY ([ID]),
	CONSTRAINT FK_SONG_AlbumID FOREIGN KEY ([AlbumID]) REFERENCES [ALBUM] ([ID])
);

CREATE TABLE [SONG_GENRE] (
	[SongID]		UNIQUEIDENTIFIER NOT NULL,
	[GenreID]		UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT FK_SONG_GENRE_SongID FOREIGN KEY ([SongID]) REFERENCES [SONG] ([ID]),
	CONSTRAINT FK_SONG_GENRE_GenreID FOREIGN KEY ([GenreID]) REFERENCES [GENRE] ([ID]),
	CONSTRAINT PK_SONG_GENRE PRIMARY KEY ([SongID], [GenreID])
);

CREATE TABLE [USER] (
	[ID]		UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[Name]		NVARCHAR(128)

	CONSTRAINT PK_USER PRIMARY KEY ([ID])
);

CREATE TABLE [STREAM] (
	[ID]			UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
	[UserID]		UNIQUEIDENTIFIER,
	[SongID]		UNIQUEIDENTIFIER,
	[StartedAt]		DATETIME,
	[FinishedAt]	DATETIME,
	[Duration]		INT NULL

	CONSTRAINT PK_STREAM PRIMARY KEY ([ID])
	CONSTRAINT FK_STREAM_UserID FOREIGN KEY (UserID) REFERENCES [USER] ([ID]),
	CONSTRAINT FK_STREAM_SongID FOREIGN KEY (SongID) REFERENCES [SONG] ([ID])
);

CREATE INDEX idx_ARTIST_Name
ON [ARTIST] ([Name]);

CREATE INDEX idx_ALBUM_Name
ON [ALBUM] ([Name]);

CREATE INDEX idx_SONG_Title
ON [SONG] ([Title]);

CREATE INDEX idx_USER_Name
ON [USER] ([Name]);